const emojipedia = [
  { id: 1, emoji: "💪", name: "Tense Biceps", meaning: "You can do it! Strength, motivation, fitness." },
  { id: 2, emoji: "🙏", name: "Folded Hands", meaning: "Prayer, gratitude, asking, hope, high five." },
  { id: 3, emoji: "🤣", name: "Rolling on the Floor Laughing", meaning: "Extreme laughter, very funny." },
  { id: 4, emoji: "😊", name: "Smiling Face with Smiling Eyes", meaning: "Happy, friendly, warm." },
  { id: 5, emoji: "😢", name: "Crying Face", meaning: "Sadness, hurt, sorrow." },
  { id: 6, emoji: "😡", name: "Pouting Face", meaning: "Angry, annoyed, frustrated." },
  { id: 7, emoji: "😮", name: "Face with Open Mouth", meaning: "Surprise, wow, shock." },
  { id: 8, emoji: "😴", name: "Sleeping Face", meaning: "Tired, sleepy, boredom." },
  { id: 9, emoji: "👍", name: "Thumbs Up", meaning: "Approval, good job, yes." },
  { id: 10, emoji: "👎", name: "Thumbs Down", meaning: "Disapproval, no, dislike." },
  { id: 11, emoji: "❤️", name: "Red Heart", meaning: "Love, affection, passion." },
  { id: 12, emoji: "😂", name: "Face with Tears of Joy", meaning: "Laughing so hard, funny." },
  { id: 13, emoji: "🙌", name: "Raising Hands", meaning: "Celebration, praise, joy." },
  { id: 14, emoji: "👏", name: "Clapping Hands", meaning: "Applause, congrats, approval." },
  { id: 15, emoji: "😎", name: "Smiling Face with Sunglasses", meaning: "Cool, confident, relaxed." },
  { id: 16, emoji: "🥳", name: "Partying Face", meaning: "Party, celebration, excitement." },
  { id: 17, emoji: "🤔", name: "Thinking Face", meaning: "Thinking, questioning, consideration." },
  { id: 18, emoji: "🤗", name: "Hugging Face", meaning: "Hug, care, affection." },
  { id: 19, emoji: "😏", name: "Smirking Face", meaning: "Smug, suggestive, sly." },
  { id: 20, emoji: "😢", name: "Crying Face", meaning: "Sad, hurt, upset." },
  { id: 21, emoji: "😬", name: "Grimacing Face", meaning: "Awkward, cringe, nervous." },
  { id: 22, emoji: "😜", name: "Winking Face with Tongue", meaning: "Playful, joking, teasing." },
  { id: 23, emoji: "😔", name: "Pensive Face", meaning: "Sad, thoughtful, reflective." },
  { id: 24, emoji: "😇", name: "Smiling Face with Halo", meaning: "Innocent, angelic, good." },
  { id: 25, emoji: "🤩", name: "Star-Struck", meaning: "Amazed, starry-eyed." },
  { id: 26, emoji: "🤯", name: "Exploding Head", meaning: "Mind blown, shocking." },
  { id: 27, emoji: "😤", name: "Face with Steam From Nose", meaning: "Frustrated, determined." },
  { id: 28, emoji: "😱", name: "Face Screaming in Fear", meaning: "Fear, horror, shock." },
  { id: 29, emoji: "🤐", name: "Zipper-Mouth Face", meaning: "Secret, quiet, cannot speak." },
  { id: 30, emoji: "😷", name: "Face with Medical Mask", meaning: "Sick, health, doctor, protection." },
  { id: 31, emoji: "🤒", name: "Face with Thermometer", meaning: "Sick, fever, ill." },
  { id: 32, emoji: "🤕", name: "Face with Head-Bandage", meaning: "Injured, hurt." },
  { id: 33, emoji: "😵", name: "Dizzy Face", meaning: "Dizzy, stunned, overwhelmed." },
  { id: 34, emoji: "🥴", name: "Woozy Face", meaning: "Drunk, unwell, dazed." },
  { id: 35, emoji: "🤮", name: "Face Vomiting", meaning: "Disgust, nausea." },
  { id: 36, emoji: "😎", name: "Smiling Face with Sunglasses", meaning: "Cool, chill." },
  { id: 37, emoji: "😴", name: "Sleeping Face", meaning: "Asleep, bored." },
  { id: 38, emoji: "🥱", name: "Yawning Face", meaning: "Tired, sleepy." },
  { id: 39, emoji: "🤤", name: "Drooling Face", meaning: "Hungry, desire." },
  { id: 40, emoji: "🤢", name: "Nauseated Face", meaning: "Disgust, nauseous." },
  { id: 41, emoji: "😪", name: "Sleepy Face", meaning: "Very sleepy." },
  { id: 42, emoji: "😵‍💫", name: "Face with Spiral Eyes", meaning: "Confused, dizzy." },
  { id: 43, emoji: "🥵", name: "Hot Face", meaning: "Overheated, hot environment." },
  { id: 44, emoji: "🥶", name: "Cold Face", meaning: "Freezing, cold environment." },
  { id: 45, emoji: "🥳", name: "Partying Face", meaning: "Party, celebration." },
  { id: 46, emoji: "🤠", name: "Cowboy Hat Face", meaning: "Cowboy, adventurous." },
  { id: 47, emoji: "🥸", name: "Disguised Face", meaning: "Incognito, disguise." },
  { id: 48, emoji: "🧐", name: "Face with Monocle", meaning: "Inspecting, scrutinizing." },
  { id: 49, emoji: "🤓", name: "Nerd Face", meaning: "Geeky, smart." },
  { id: 50, emoji: "😈", name: "Smiling Face with Horns", meaning: "Mischievous, playful devil." },
  { id: 51, emoji: "😇", name: "Smiling Face with Halo", meaning: "Innocent, good." },
  { id: 52, emoji: "👻", name: "Ghost", meaning: "Spooky, playful ghost." },
  { id: 53, emoji: "💩", name: "Pile of Poo", meaning: "Silly, funny, gross." },
  { id: 54, emoji: "😺", name: "Smiling Cat Face", meaning: "Happy cat." },
  { id: 55, emoji: "😸", name: "Grinning Cat Face with Smiling Eyes", meaning: "Joyful cat." },
  { id: 56, emoji: "😹", name: "Cat Face with Tears of Joy", meaning: "Laughing cat." },
  { id: 57, emoji: "😻", name: "Smiling Cat Face with Heart-Eyes", meaning: "Love, adoration (cat)." },
  { id: 58, emoji: "😼", name: "Cat Face with Wry Smile", meaning: "Sly cat." },
  { id: 59, emoji: "😽", name: "Kissing Cat Face", meaning: "Affection (cat)." },
  { id: 60, emoji: "🙀", name: "Weary Cat Face", meaning: "Shock, fear (cat)." },
  { id: 61, emoji: "😿", name: "Crying Cat Face", meaning: "Sad (cat)." },
  { id: 62, emoji: "😾", name: "Pouting Cat Face", meaning: "Angry, frustrated cat." },
  { id: 63, emoji: "🐶", name: "Dog Face", meaning: "Friendly dog." },
  { id: 64, emoji: "🐱", name: "Cat Face", meaning: "Generic cat." },
  { id: 65, emoji: "🐭", name: "Mouse Face", meaning: "Cute mouse." },
  { id: 66, emoji: "🐹", name: "Hamster Face", meaning: "Cute hamster." },
  { id: 67, emoji: "🐰", name: "Rabbit Face", meaning: "Cute rabbit." },
  { id: 68, emoji: "🦊", name: "Fox Face", meaning: "Cunning or cute fox." },
  { id: 69, emoji: "🐻", name: "Bear Face", meaning: "Friendly bear." },
  { id: 70, emoji: "🐼", name: "Panda Face", meaning: "Panda, cuteness." },
  { id: 71, emoji: "🦁", name: "Lion Face", meaning: "Lion, brave." },
  { id: 72, emoji: "🐯", name: "Tiger Face", meaning: "Tiger, strong." },
  { id: 73, emoji: "🐨", name: "Koala Face", meaning: "Koala, cute." },
  { id: 74, emoji: "🐸", name: "Frog Face", meaning: "Frog, amphibian." },
  { id: 75, emoji: "🦄", name: "Unicorn Face", meaning: "Magic, fantasy." },
  { id: 76, emoji: "🐝", name: "Honeybee", meaning: "Bee, nature." },
  { id: 77, emoji: "🐞", name: "Lady Beetle", meaning: "Ladybug, nature." },
  { id: 78, emoji: "🦋", name: "Butterfly", meaning: "Butterfly, transformation." },
  { id: 79, emoji: "🐢", name: "Turtle", meaning: "Turtle, slow, Turtle." },
  { id: 80, emoji: "🐍", name: "Snake", meaning: "Snake, reptile." },
  { id: 81, emoji: "🐙", name: "Octopus", meaning: "Octopus, sea." },
  { id: 82, emoji: "🦀", name: "Crab", meaning: "Crab, sea." },
  { id: 83, emoji: "🐠", name: "Tropical Fish", meaning: "Fish, ocean." },
  { id: 84, emoji: "🐳", name: "Spouting Whale", meaning: "Whale, sea." },
  { id: 85, emoji: "🐬", name: "Dolphin", meaning: "Dolphin, sea." },
  { id: 86, emoji: "🌎", name: "Globe Showing Americas", meaning: "Earth, world." },
  { id: 87, emoji: "🌞", name: "Sun with Face", meaning: "Sunny, warm." },
  { id: 88, emoji: "⭐", name: "Star", meaning: "Star, excellence." },
  { id: 89, emoji: "⚡", name: "High Voltage", meaning: "Energy, lightning." },
  { id: 90, emoji: "🔥", name: "Fire", meaning: "Hot, trending." },
  { id: 91, emoji: "✨", name: "Sparkles", meaning: "Sparkle, magical, clean." },
  { id: 92, emoji: "🌈", name: "Rainbow", meaning: "LGBTQ+, hope." },
  { id: 93, emoji: "☂️", name: "Umbrella", meaning: "Rain." },
  { id: 94, emoji: "❄️", name: "Snowflake", meaning: "Cold, uniqueness." },
  { id: 95, emoji: "🌸", name: "Cherry Blossom", meaning: "Beauty, spring." },
  { id: 96, emoji: "🌵", name: "Cactus", meaning: "Desert, resilience." },
  { id: 97, emoji: "🌊", name: "Water Wave", meaning: "Ocean, wave." },
  { id: 98, emoji: "🍎", name: "Red Apple", meaning: "Apple, fruit, health." },
  { id: 99, emoji: "🍕", name: "Pizza", meaning: "Pizza, food, delicious." },
  { id: 100, emoji: "☕", name: "Hot Beverage", meaning: "Coffee, tea, warmth." },
  { id: 101, emoji: "🖤", name: "Black Heart", meaning: "Mourning, sorrow, dark humor, gothic vibe." },
  { id: 102, emoji: "🤍", name: "White Heart", meaning: "Purity, love, peace, spiritual love." },
  { id: 103, emoji: "🤎", name: "Brown Heart", meaning: "Warmth, earthiness, friendship, natural." },
  { id: 104, emoji: "💙", name: "Blue Heart", meaning: "Trust, loyalty, peace, water or sadness." },
  { id: 105, emoji: "💚", name: "Green Heart", meaning: "Nature, growth, health, envy." },
  { id: 106, emoji: "💛", name: "Yellow Heart", meaning: "Friendship, happiness, warmth, optimism." },
  { id: 107, emoji: "💜", name: "Purple Heart", meaning: "Love, compassion, creativity, royalty." },
  { id: 108, emoji: "🧡", name: "Orange Heart", meaning: "Energy, warmth, fun, autumn." },
  { id: 109, emoji: "💔", name: "Broken Heart", meaning: "Sadness, heartbreak, loss." },
  { id: 110, emoji: "💕", name: "Two Hearts", meaning: "Romantic love, affection, love multiplied." },
  { id: 111, emoji: "🎉", name: "Party Popper", meaning: "Celebration, excitement, party time!" },
  { id: 112, emoji: "🥳", name: "Partying Face", meaning: "Happiness, celebrations, festive mood." },
  { id: 113, emoji: "🤯", name: "Exploding Head", meaning: "Mind blown, shock, astonishment." },
  { id: 114, emoji: "🤔", name: "Thinking Face", meaning: "Pondering, questioning, deep thought." },
  { id: 115, emoji: "🙄", name: "Face With Rolling Eyes", meaning: "Sarcasm, annoyance, disbelief." },
  { id: 116, emoji: "😇", name: "Smiling Face with Halo", meaning: "Innocence, good deeds, angelic behavior." },
  { id: 117, emoji: "🥺", name: "Pleading Face", meaning: "Begging, cuteness, emotional request." },
  { id: 118, emoji: "🤤", name: "Drooling Face", meaning: "Delicious food, attraction, desire." },
  { id: 119, emoji: "🤢", name: "Nauseated Face", meaning: "Disgust, sickness, grossed out." },
  { id: 120, emoji: "🤮", name: "Face Vomiting", meaning: "Extreme disgust, illness, bad reaction." },
  { id: 121, emoji: "🤧", name: "Sneezing Face", meaning: "Sneezing, sickness, allergies." },
  { id: 122, emoji: "🤒", name: "Face with Thermometer", meaning: "Feeling sick, fever." },
  { id: 123, emoji: "🤕", name: "Face with Head-Bandage", meaning: "Injury, not feeling well." },
  { id: 124, emoji: "🥶", name: "Cold Face", meaning: "Freezing, extreme cold, chills." },
  { id: 125, emoji: "🥵", name: "Hot Face", meaning: "Extreme heat, hot weather, spicy food." },
  { id: 126, emoji: "😈", name: "Smiling Face with Horns", meaning: "Mischief, playful trouble." },
  { id: 127, emoji: "👹", name: "Ogre", meaning: "Scary monster, Japanese folklore creature." },
  { id: 128, emoji: "👻", name: "Ghost", meaning: "Playful scare, spooky vibe." },
  { id: 129, emoji: "💀", name: "Skull", meaning: "Death, danger, humor (I’m dead 😂)." },
  { id: 130, emoji: "☠️", name: "Skull and Crossbones", meaning: "Danger, poison, lethal." },
  { id: 131, emoji: "🤑", name: "Money-Mouth Face", meaning: "Riches, profit, greed." },
  { id: 132, emoji: "💸", name: "Money with Wings", meaning: "Losing money, expenses, spending." },
  { id: 133, emoji: "💰", name: "Money Bag", meaning: "Wealth, profit, financial success." },
  { id: 134, emoji: "🏆", name: "Trophy", meaning: "Victory, achievement, sports win." },
  { id: 135, emoji: "🥇", name: "1st Place Medal", meaning: "Winning, gold medal, top achievement." },
  { id: 136, emoji: "🥈", name: "2nd Place Medal", meaning: "Runner-up, silver medal." },
  { id: 137, emoji: "🥉", name: "3rd Place Medal", meaning: "Third place, bronze medal." },
  { id: 138, emoji: "🎯", name: "Direct Hit", meaning: "Target, precision, accuracy." },
  { id: 139, emoji: "🛒", name: "Shopping Cart", meaning: "Shopping, online store, retail." },
  { id: 140, emoji: "📦", name: "Package", meaning: "Delivery, shipping, parcels." },
  { id: 141, emoji: "🪐", name: "Ringed Planet", meaning: "Saturn, space, astronomy." },
  { id: 142, emoji: "🚀", name: "Rocket", meaning: "Launch, space travel, progress." },
  { id: 143, emoji: "🛸", name: "Flying Saucer", meaning: "UFO, aliens, sci-fi." },
  { id: 144, emoji: "🌌", name: "Milky Way", meaning: "Night sky, galaxy." },
  { id: 145, emoji: "🌠", name: "Shooting Star", meaning: "Wish, dream, magic." },
  { id: 146, emoji: "🌙", name: "Crescent Moon", meaning: "Night, sleep, dreams." },
  { id: 147, emoji: "🌓", name: "First Quarter Moon", meaning: "Moon phase, astronomy." },
  { id: 148, emoji: "🌕", name: "Full Moon", meaning: "Night, lunar events." },
  { id: 149, emoji: "🌑", name: "New Moon", meaning: "Beginnings, mystery." },
  { id: 150, emoji: "☀️", name: "Sun", meaning: "Sunny, warmth, energy." },
  { id: 151, emoji: "🌤️", name: "Sun Behind Small Cloud", meaning: "Partly sunny." },
  { id: 152, emoji: "🌧️", name: "Cloud with Rain", meaning: "Rainy weather." },
  { id: 153, emoji: "🌩️", name: "Cloud with Lightning", meaning: "Storm, thunder." },
  { id: 154, emoji: "🌪️", name: "Tornado", meaning: "Storm, danger." },
  { id: 155, emoji: "🌫️", name: "Fog", meaning: "Low visibility, mystery." },
  { id: 156, emoji: "🌋", name: "Volcano", meaning: "Eruption, mountain." },
  { id: 157, emoji: "🏔️", name: "Snow-Capped Mountain", meaning: "Winter, adventure." },
  { id: 158, emoji: "🏝️", name: "Desert Island", meaning: "Vacation, solitude." },
  { id: 159, emoji: "🏜️", name: "Desert", meaning: "Hot, arid, dry." },
  { id: 160, emoji: "🏕️", name: "Camping", meaning: "Outdoors, travel, tents." },
  { id: 161, emoji: "🏟️", name: "Stadium", meaning: "Sports, events." },
  { id: 162, emoji: "🏖️", name: "Beach with Umbrella", meaning: "Summer, relaxation." },
  { id: 163, emoji: "🏞️", name: "National Park", meaning: "Nature, scenery." },
  { id: 164, emoji: "🏙️", name: "Cityscape", meaning: "Urban, buildings." },
  { id: 165, emoji: "🏛️", name: "Classical Building", meaning: "Museum, history." },
  { id: 166, emoji: "🕌", name: "Mosque", meaning: "Islam, prayer." },
  { id: 167, emoji: "⛪", name: "Church", meaning: "Christianity, worship." },
  { id: 168, emoji: "🕍", name: "Synagogue", meaning: "Judaism, religion." },
  { id: 169, emoji: "🕋", name: "Kaaba", meaning: "Islam, pilgrimage." },
  { id: 170, emoji: "🗽", name: "Statue of Liberty", meaning: "Freedom, USA." },
  { id: 171, emoji: "🗼", name: "Tokyo Tower", meaning: "Japan, landmark." },
  { id: 172, emoji: "🗿", name: "Moai", meaning: "Easter Island, mystery." },
  { id: 173, emoji: "🎡", name: "Ferris Wheel", meaning: "Amusement park, fun." },
  { id: 174, emoji: "🎢", name: "Roller Coaster", meaning: "Thrill, fun." },
  { id: 175, emoji: "🎠", name: "Carousel Horse", meaning: "Fair, amusement park." },
  { id: 176, emoji: "🚂", name: "Locomotive", meaning: "Train travel." },
  { id: 177, emoji: "✈️", name: "Airplane", meaning: "Travel, flight." },
  { id: 178, emoji: "🚁", name: "Helicopter", meaning: "Air travel." },
  { id: 179, emoji: "🚢", name: "Ship", meaning: "Sea travel, cruise." },
  { id: 180, emoji: "🛳️", name: "Passenger Ship", meaning: "Cruise, ferry." },
  { id: 181, emoji: "🚤", name: "Speedboat", meaning: "Water sports." },
  { id: 182, emoji: "🛶", name: "Canoe", meaning: "Adventure, boating." },
  { id: 183, emoji: "🚲", name: "Bicycle", meaning: "Cycling, eco-friendly travel." },
  { id: 184, emoji: "🏍️", name: "Motorcycle", meaning: "Riding, adventure." },
  { id: 185, emoji: "🚗", name: "Car", meaning: "Driving, travel." },
  { id: 186, emoji: "🚓", name: "Police Car", meaning: "Law enforcement." },
  { id: 187, emoji: "🚑", name: "Ambulance", meaning: "Medical emergency." },
  { id: 188, emoji: "🚒", name: "Fire Engine", meaning: "Firefighters, emergency." },
  { id: 189, emoji: "🚌", name: "Bus", meaning: "Public transport." },
  { id: 190, emoji: "🚍", name: "Oncoming Bus", meaning: "Bus coming toward you." },
  { id: 191, emoji: "🚎", name: "Trolleybus", meaning: "Electric bus, public transport." },
  { id: 192, emoji: "🏎️", name: "Racing Car", meaning: "Speed, competition." },
  { id: 193, emoji: "🚜", name: "Tractor", meaning: "Farming, agriculture." },
  { id: 194, emoji: "🛴", name: "Kick Scooter", meaning: "Casual transport, fun." },
  { id: 195, emoji: "🛹", name: "Skateboard", meaning: "Skating, tricks, street sport." },
  { id: 196, emoji: "🎿", name: "Skis", meaning: "Winter sport, skiing." },
  { id: 197, emoji: "🏄‍♂️", name: "Man Surfing", meaning: "Surfing, ocean sport." },
  { id: 198, emoji: "🏊‍♀️", name: "Woman Swimming", meaning: "Swimming, water activity." },
  { id: 199, emoji: "🚵‍♂️", name: "Man Mountain Biking", meaning: "Cycling, adventure sport." },
  { id: 200, emoji: "🤹‍♀️", name: "Woman Juggling", meaning: "Multitasking, performance, circus." },
  { id: 201, emoji: "🫠", name: "Melting Face", meaning: "Sarcasm, embarrassment, extreme heat." },
{ id: 202, emoji: "🌝", name: "Full Moon Face", meaning: "Full moon with face, playful or eerie." },
{ id: 203, emoji: "🌚", name: "New Moon Face", meaning: "Night, secrecy, awkwardness." }


];

export default emojipedia;